### ISSUE TITLE
Update for CUDA 12.3.2

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-feedstock#15]
Using this issue to track updates pertaining to CUDA 12.3.2

**Comment by jakirkham** [comment]
Currently this is waiting on completion of the CUDA 12.2.2 updates: https://github.com/conda-forge/cuda-feedstock/issues/13

Once that is done and we are fairly confident it is working correctly, we will look into the next update

**Comment by jakirkham** [comment]
We've just completed CUDA 12.2.2. Going to let that simmer for a bit to see how things look

Once we feel confident with CUDA 12.2.2, we will start working on CUDA 12.3.1

**Comment by adibbley** [comment]
12.3.2 was posted last week, we should be updating to that.

**Comment by danpetry** [comment]
How long were you thinking for a time period to let things simmer? I'm wondering whether to wait and follow the 12.3.2 update with associated releases in defaults, or proceed with 12.2.

**Comment by danpetry** [comment]
Well, that answers that!

**Comment by jakirkham** [comment]
The bulk of these are in

We ran into an issue with `cuda-sanitizer-api` ( https://github.com/conda-forge/cuda-sanitizer-api-feedstock/pull/5 ). There are a couple metapackages that depend on it that are blocked atm

Will take a closer look tomorrow

**Comment by jakirkham** [comment]
Closing as completed
