### ISSUE TITLE
Migrate CTK packages to `{{ stdlib("c") }}`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-feedstock#26]
The `sysroot*` syntax used currently by CTK recipes is getting phased out

Sample syntax as seen [currently in `libcublas`]( https://github.com/conda-forge/libcublas-feedstock/blob/f2fd8b60ec8eb2ad07988b1182ebba4ac12a9c93/recipe/meta.yaml#L58 ):

```yaml
        - sysroot_{{ target_platform }} 2.17    # [linux]
```

<hr>

The recommendation is to move to `{{ stdlib("c") }}` ( https://github.com/conda-forge/conda-forge.github.io/issues/2102 )

The simplest way to make this change would be to add the following to `conda-forge.yml` files:

```yaml
os_version:
  linux_64: cos7
  linux_aarch64: cos7
  linux_ppc64le: cos7
```

Make the following change to `recipe/meta.yaml`

```diff + yaml
-        - sysroot_{{ target_platform }} 2.17    # [linux]
+        - {{ stdlib("c") }}
```

Then [re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks )

**Comment by h-vetinari** [comment]
> The simplest way to make this change would be to add the following to `conda-forge.yml` files:
> 
> ```yaml
> os_version:
>   linux_64: cos7
>   linux_aarch64: cos7
>   linux_ppc64le: cos7
> ```

That change shouldn't be necessary for the stdlib-migration - if it ran fine before without setting `os_version`, it should work fine after adding replacing `sysroot_{{ ... }}` with `{{ stdlib("c") }}` and setting
```
c_stdlib_version:  # [linux]
 - "2.17"          # [linux]
```
in `recipe/conda_build_config.yaml`. The only reason (to my knowledge) where it'd be necessary to override `os_version` is if a newer glibc is required to actually execute things (e.g. testing the package, as our build deps generally don't require newer symbols so far).

**Comment by jakirkham** [comment]
As the CTK packages already require 2.17, it seems reasonable to add `os_version` in this case

Agree that other cases may not need this
