### ISSUE TITLE
C11 compiler NVC

### ISSUE THREAD

**Issue by berceanu** [conda-forge/cuda-feedstock#6]
### Comment:

Is there any conda package that includes `NVC`, NVIDIA's C11 compiler? I know it is included in the HPC SDK (https://docs.nvidia.com/hpc-sdk//index.html) and I know `NVCC` is on conda (`nvidia/cuda-nvcc`), but I wasn't able to find `NVC`.

**Comment by jakirkham** [comment]
Thanks for the request! 🙏

Let's keep the discussion in the HPC SDK issue: https://github.com/conda-forge/conda-forge.github.io/issues/1390
